
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class QueFour extends java.awt.Frame {

    /**
     * Creates new form QueFour
     */
    public QueFour() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        label1 = new java.awt.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        button1.setLabel("click me");
        button1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                button1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                button1FocusLost(evt);
            }
        });

        button2.setLabel("Click Me");
        button2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                button2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                button2FocusLost(evt);
            }
        });

        button3.setLabel("Choose me");
        button3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                button3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                button3FocusLost(evt);
            }
        });

        label1.setText("Choose me");
        label1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                label1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                label1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_button1FocusGained
        button1.setBackground(Color.GREEN);
    }//GEN-LAST:event_button1FocusGained

    private void button1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_button1FocusLost
        button1.setBackground(Color.CYAN);
    }//GEN-LAST:event_button1FocusLost

    private void button2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_button2FocusGained
        // TODO add your handling code here:
        button2.setBackground(Color.GREEN );
    }//GEN-LAST:event_button2FocusGained

    private void button2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_button2FocusLost
        button2.setBackground(Color.CYAN);
    }//GEN-LAST:event_button2FocusLost

    private void button3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_button3FocusGained
        button3.setBackground(Color.GREEN);
    }//GEN-LAST:event_button3FocusGained

    private void button3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_button3FocusLost
        button3.setBackground(Color.CYAN);
    }//GEN-LAST:event_button3FocusLost

    private void label1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_label1FocusGained
        label1.setBackground(Color.GREEN);
    }//GEN-LAST:event_label1FocusGained

    private void label1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_label1FocusLost
        label1.setBackground(Color.CYAN);
    }//GEN-LAST:event_label1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueFour().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
